FROM alpine:3 AS builder

RUN apk update && apk add curl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/kubectl

FROM alpine:3 AS final

COPY --from=builder /usr/local/bin/kubectl /usr/local/bin/kubectl