apiVersion: netbird.io/v1alpha1
kind: NetworkRouter
metadata:
  name: netbird
  namespace: netbird
spec:
  dnsZoneRef:
    name: cluster.local
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: netbird-public
spec:
  controllerName: "gateway.netbird.io/controller"
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: netbird-private
spec:
  controllerName: "gateway.netbird.io/controller"
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: private
  namespace: netbird
spec:
  gatewayClassName: netbird-private
  listeners:
  - protocol: gateway.netbird.io/NetworkRouter
    name: netbird
    port: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public
  namespace: netbird
spec:
  gatewayClassName: netbird-public
  listeners:
  - protocol: gateway.netbird.io/NetworkRouter
    name: netbird
    port: 1
