apiVersion: netbird.io/v1alpha1
kind: NetworkEgress
metadata:
  name: nginx
  namespace: default
spec:
  networkRouterRef:
    name: prod
    namespace: netbird
  target:
    fqdn:
      hostname: nginx.default.prod.company.internal
  ports:
    - name: http
      port: 80
