name: Bug Report
description: Report a bug in NetBird Operator.
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill ot this bug report! Please check previous issues and discussions before submitting a new issue.
  - type: input
    attributes:
      label: NetBird Operator Version
      placeholder: eg. v0.4.0
    validations:
      required: true
  - type: input
    attributes:
      label: Kubernetes Version
      placeholder: eg. v1.36.0
    validations:
      required: true
  - type: input
    attributes:
      label: CNI
      placeholder: eg. Calico, Cilium, Azure CNI...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is.
    validations:
      required: true
