apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "netbird-operator.fullname" . }}-delete-routers
  labels:
    app.kubernetes.io/component: operator
    {{- include "netbird-operator.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backOffLimit: 3
  template:
    metadata:
      name: {{ include "netbird-operator.fullname" . }}
      labels:
        app.kubernetes.io/component: operator
        {{- include "netbird-operator.labels" . | nindent 8 }}
        {{- with .Values.operator.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: pre-delete
        image: "bitnami/kubectl:latest"
        args:
        - delete
        - --all
        - -A
        - --cascade=foreground
        - --ignore-not-found
        - NBRoutingPeer
      serviceAccountName: {{ include "netbird-operator.serviceAccountName" . }}
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "netbird-operator.fullname" . }}-delete-policies
  labels:
    app.kubernetes.io/component: operator
    {{- include "netbird-operator.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backOffLimit: 3
  template:
    metadata:
      name: {{ include "netbird-operator.fullname" . }}
      labels:
        app.kubernetes.io/component: operator
        {{- include "netbird-operator.labels" . | nindent 8 }}
        {{- with .Values.operator.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: pre-delete
        image: "bitnami/kubectl:latest"
        args:
        - delete
        - --all
        - --cascade=foreground
        - --ignore-not-found
        - NBPolicy
      serviceAccountName: {{ include "netbird-operator.serviceAccountName" . }}
      restartPolicy: Never
---