apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "netbird-operator.fullname" . }}
  labels:
    {{- include "netbird-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - netbird.io
  resources:
  - nbsetupkeys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netbird.io
  resources:
  - nbsetupkeys/finalizers
  verbs:
  - update
- apiGroups:
  - netbird.io
  resources:
  - nbsetupkeys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
{{- if .Values.clusterSecretsPermissions.allowAllSecrets }}
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "netbird-operator.fullname" . }}
  labels:
    {{- include "netbird-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "netbird-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "netbird-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "netbird-operator.fullname" . }}
  labels:
    {{- include "netbird-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "netbird-operator.fullname" . }}
  labels:
    {{- include "netbird-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "netbird-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "netbird-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
