{{- if .Values.netbirdAPI.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbird-operator.fullname" . }}
  labels:
    app.kubernetes.io/component: operator
    {{- include "netbird-operator.labels" . | nindent 4 }}
stringData:
  NB_API_KEY: {{ .Values.netbirdAPI.key }}
{{- end }}