// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AccessRestrictionsApplyConfiguration represents a declarative configuration of the AccessRestrictions type for use
// with apply.
//
// AccessRestrictions are connection-level restrictions based on IP address or
// geography, applied to the reverse-proxy service.
type AccessRestrictionsApplyConfiguration struct {
	// AllowedCidrs is a CIDR allowlist. If non-empty, only matching source IPs
	// are allowed. Evaluated before BlockedCidrs.
	AllowedCidrs []string `json:"allowedCidrs,omitempty"`
	// BlockedCidrs is a CIDR blocklist. Matching source IPs are rejected.
	BlockedCidrs []string `json:"blockedCidrs,omitempty"`
	// AllowedCountries is an ISO 3166-1 alpha-2 country-code allowlist. If
	// non-empty, only these countries are permitted.
	AllowedCountries []string `json:"allowedCountries,omitempty"`
	// BlockedCountries is an ISO 3166-1 alpha-2 country-code blocklist.
	BlockedCountries []string `json:"blockedCountries,omitempty"`
}

// AccessRestrictionsApplyConfiguration constructs a declarative configuration of the AccessRestrictions type for use with
// apply.
func AccessRestrictions() *AccessRestrictionsApplyConfiguration {
	return &AccessRestrictionsApplyConfiguration{}
}

// WithAllowedCidrs adds the given value to the AllowedCidrs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedCidrs field.
func (b *AccessRestrictionsApplyConfiguration) WithAllowedCidrs(values ...string) *AccessRestrictionsApplyConfiguration {
	for i := range values {
		b.AllowedCidrs = append(b.AllowedCidrs, values[i])
	}
	return b
}

// WithBlockedCidrs adds the given value to the BlockedCidrs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BlockedCidrs field.
func (b *AccessRestrictionsApplyConfiguration) WithBlockedCidrs(values ...string) *AccessRestrictionsApplyConfiguration {
	for i := range values {
		b.BlockedCidrs = append(b.BlockedCidrs, values[i])
	}
	return b
}

// WithAllowedCountries adds the given value to the AllowedCountries field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedCountries field.
func (b *AccessRestrictionsApplyConfiguration) WithAllowedCountries(values ...string) *AccessRestrictionsApplyConfiguration {
	for i := range values {
		b.AllowedCountries = append(b.AllowedCountries, values[i])
	}
	return b
}

// WithBlockedCountries adds the given value to the BlockedCountries field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BlockedCountries field.
func (b *AccessRestrictionsApplyConfiguration) WithBlockedCountries(values ...string) *AccessRestrictionsApplyConfiguration {
	for i := range values {
		b.BlockedCountries = append(b.BlockedCountries, values[i])
	}
	return b
}
