// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// CrossNamespaceReferenceApplyConfiguration represents a declarative configuration of the CrossNamespaceReference type for use
// with apply.
type CrossNamespaceReferenceApplyConfiguration struct {
	// Name of the referent.
	Name *string `json:"name,omitempty"`
	// Namespace of the referent.
	Namespace *string `json:"namespace,omitempty"`
}

// CrossNamespaceReferenceApplyConfiguration constructs a declarative configuration of the CrossNamespaceReference type for use with
// apply.
func CrossNamespaceReference() *CrossNamespaceReferenceApplyConfiguration {
	return &CrossNamespaceReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *CrossNamespaceReferenceApplyConfiguration) WithName(value string) *CrossNamespaceReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *CrossNamespaceReferenceApplyConfiguration) WithNamespace(value string) *CrossNamespaceReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}
