// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DNSRecordStatusApplyConfiguration represents a declarative configuration of the DNSRecordStatus type for use
// with apply.
//
// DNSRecordStatus tracks a single DNS record managed for a NetworkResource.
type DNSRecordStatusApplyConfiguration struct {
	// Type is the record type (A or AAAA).
	Type *string `json:"type,omitempty"`
	// Content is the record content (the ClusterIP).
	Content *string `json:"content,omitempty"`
	// ID is the Netbird DNS record id.
	ID *string `json:"id,omitempty"`
}

// DNSRecordStatusApplyConfiguration constructs a declarative configuration of the DNSRecordStatus type for use with
// apply.
func DNSRecordStatus() *DNSRecordStatusApplyConfiguration {
	return &DNSRecordStatusApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *DNSRecordStatusApplyConfiguration) WithType(value string) *DNSRecordStatusApplyConfiguration {
	b.Type = &value
	return b
}

// WithContent sets the Content field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Content field is set to the value of the last call.
func (b *DNSRecordStatusApplyConfiguration) WithContent(value string) *DNSRecordStatusApplyConfiguration {
	b.Content = &value
	return b
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *DNSRecordStatusApplyConfiguration) WithID(value string) *DNSRecordStatusApplyConfiguration {
	b.ID = &value
	return b
}
