// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// FQDNTargetApplyConfiguration represents a declarative configuration of the FQDNTarget type for use
// with apply.
//
// FQDNTarget matches traffic by an exact domain name (no wildcards).
type FQDNTargetApplyConfiguration struct {
	// Hostname is a fully qualified domain name to match exactly.
	Hostname *string `json:"hostname,omitempty"`
}

// FQDNTargetApplyConfiguration constructs a declarative configuration of the FQDNTarget type for use with
// apply.
func FQDNTarget() *FQDNTargetApplyConfiguration {
	return &FQDNTargetApplyConfiguration{}
}

// WithHostname sets the Hostname field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hostname field is set to the value of the last call.
func (b *FQDNTargetApplyConfiguration) WithHostname(value string) *FQDNTargetApplyConfiguration {
	b.Hostname = &value
	return b
}
