// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// GroupSpecApplyConfiguration represents a declarative configuration of the GroupSpec type for use
// with apply.
//
// GroupSpec defines the desired state of Group.
type GroupSpecApplyConfiguration struct {
	// Name of the group.
	Name *string `json:"name,omitempty"`
}

// GroupSpecApplyConfiguration constructs a declarative configuration of the GroupSpec type for use with
// apply.
func GroupSpec() *GroupSpecApplyConfiguration {
	return &GroupSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *GroupSpecApplyConfiguration) WithName(value string) *GroupSpecApplyConfiguration {
	b.Name = &value
	return b
}
