// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// IPAddressTargetApplyConfiguration represents a declarative configuration of the IPAddressTarget type for use
// with apply.
//
// IPAddressTarget is a single IPv4 or IPv6 address.
type IPAddressTargetApplyConfiguration struct {
	// Address is a single IP address, e.g. "10.0.0.5" or "2001:db8::1".
	// CIDR notation (e.g. "10.0.0.0/24") is rejected.
	Address *string `json:"address,omitempty"`
}

// IPAddressTargetApplyConfiguration constructs a declarative configuration of the IPAddressTarget type for use with
// apply.
func IPAddressTarget() *IPAddressTargetApplyConfiguration {
	return &IPAddressTargetApplyConfiguration{}
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *IPAddressTargetApplyConfiguration) WithAddress(value string) *IPAddressTargetApplyConfiguration {
	b.Address = &value
	return b
}
