// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// IPTargetApplyConfiguration represents a declarative configuration of the IPTarget type for use
// with apply.
//
// IPTarget is a single IPv4 or IPv6 address.
type IPTargetApplyConfiguration struct {
	// Address is a single IP address.
	Address *string `json:"address,omitempty"`
}

// IPTargetApplyConfiguration constructs a declarative configuration of the IPTarget type for use with
// apply.
func IPTarget() *IPTargetApplyConfiguration {
	return &IPTargetApplyConfiguration{}
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *IPTargetApplyConfiguration) WithAddress(value string) *IPTargetApplyConfiguration {
	b.Address = &value
	return b
}
