// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/netbirdio/kubernetes-operator/api/v1alpha1"
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// NBServicePolicySpecApplyConfiguration represents a declarative configuration of the NBServicePolicySpec type for use
// with apply.
//
// NBServicePolicySpec defines the desired state of NBServicePolicy.
type NBServicePolicySpecApplyConfiguration struct {
	// TargetRefs identify the HTTPRoute(s) this policy attaches to, following
	// the Gateway API direct policy-attachment pattern (GEP-713). Each target
	// must be an HTTPRoute in the same namespace as the policy.
	TargetRefs []v1.LocalPolicyTargetReference `json:"targetRefs,omitempty"`
	// Private, when true, makes the service NetBird-only: inbound peers
	// authenticate via their tunnel identity (no OIDC) and an ACL policy is
	// auto-generated from AccessGroups. Requires an HTTP service.
	Private *bool `json:"private,omitempty"`
	// AccessGroups are the NetBird group IDs whose peers may reach a private
	// service over the tunnel. Required when Private is true; ignored otherwise.
	AccessGroups []string `json:"accessGroups,omitempty"`
	// CrowdsecMode sets the CrowdSec IP-reputation handling for the service.
	CrowdsecMode *apiv1alpha1.CrowdsecMode `json:"crowdsecMode,omitempty"`
	// AccessRestrictions sets IP/geo connection-level restrictions.
	AccessRestrictions *AccessRestrictionsApplyConfiguration `json:"accessRestrictions,omitempty"`
	// PassHostHeader, when true, forwards the original client Host header to
	// the backend instead of rewriting it to the backend address.
	PassHostHeader *bool `json:"passHostHeader,omitempty"`
	// RewriteRedirects, when true, rewrites Location headers in backend
	// responses to replace the backend address with the public domain.
	RewriteRedirects *bool `json:"rewriteRedirects,omitempty"`
}

// NBServicePolicySpecApplyConfiguration constructs a declarative configuration of the NBServicePolicySpec type for use with
// apply.
func NBServicePolicySpec() *NBServicePolicySpecApplyConfiguration {
	return &NBServicePolicySpecApplyConfiguration{}
}

// WithTargetRefs adds the given value to the TargetRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetRefs field.
func (b *NBServicePolicySpecApplyConfiguration) WithTargetRefs(values ...v1.LocalPolicyTargetReference) *NBServicePolicySpecApplyConfiguration {
	for i := range values {
		b.TargetRefs = append(b.TargetRefs, values[i])
	}
	return b
}

// WithPrivate sets the Private field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Private field is set to the value of the last call.
func (b *NBServicePolicySpecApplyConfiguration) WithPrivate(value bool) *NBServicePolicySpecApplyConfiguration {
	b.Private = &value
	return b
}

// WithAccessGroups adds the given value to the AccessGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AccessGroups field.
func (b *NBServicePolicySpecApplyConfiguration) WithAccessGroups(values ...string) *NBServicePolicySpecApplyConfiguration {
	for i := range values {
		b.AccessGroups = append(b.AccessGroups, values[i])
	}
	return b
}

// WithCrowdsecMode sets the CrowdsecMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CrowdsecMode field is set to the value of the last call.
func (b *NBServicePolicySpecApplyConfiguration) WithCrowdsecMode(value apiv1alpha1.CrowdsecMode) *NBServicePolicySpecApplyConfiguration {
	b.CrowdsecMode = &value
	return b
}

// WithAccessRestrictions sets the AccessRestrictions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessRestrictions field is set to the value of the last call.
func (b *NBServicePolicySpecApplyConfiguration) WithAccessRestrictions(value *AccessRestrictionsApplyConfiguration) *NBServicePolicySpecApplyConfiguration {
	b.AccessRestrictions = value
	return b
}

// WithPassHostHeader sets the PassHostHeader field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PassHostHeader field is set to the value of the last call.
func (b *NBServicePolicySpecApplyConfiguration) WithPassHostHeader(value bool) *NBServicePolicySpecApplyConfiguration {
	b.PassHostHeader = &value
	return b
}

// WithRewriteRedirects sets the RewriteRedirects field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RewriteRedirects field is set to the value of the last call.
func (b *NBServicePolicySpecApplyConfiguration) WithRewriteRedirects(value bool) *NBServicePolicySpecApplyConfiguration {
	b.RewriteRedirects = &value
	return b
}
