// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// NBServicePolicyStatusApplyConfiguration represents a declarative configuration of the NBServicePolicyStatus type for use
// with apply.
//
// NBServicePolicyStatus defines the observed state of NBServicePolicy.
type NBServicePolicyStatusApplyConfiguration struct {
	// ObservedGeneration is the last reconciled generation.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions holds the conditions for the NBServicePolicy.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// NBServicePolicyStatusApplyConfiguration constructs a declarative configuration of the NBServicePolicyStatus type for use with
// apply.
func NBServicePolicyStatus() *NBServicePolicyStatusApplyConfiguration {
	return &NBServicePolicyStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *NBServicePolicyStatusApplyConfiguration) WithObservedGeneration(value int64) *NBServicePolicyStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *NBServicePolicyStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *NBServicePolicyStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
