// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// NetworkEgressPortApplyConfiguration represents a declarative configuration of the NetworkEgressPort type for use
// with apply.
type NetworkEgressPortApplyConfiguration struct {
	// Name of the port.
	Name *string `json:"name,omitempty"`
	// The port that will be exposed by this service.
	Port *int32 `json:"port,omitempty"`
}

// NetworkEgressPortApplyConfiguration constructs a declarative configuration of the NetworkEgressPort type for use with
// apply.
func NetworkEgressPort() *NetworkEgressPortApplyConfiguration {
	return &NetworkEgressPortApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NetworkEgressPortApplyConfiguration) WithName(value string) *NetworkEgressPortApplyConfiguration {
	b.Name = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *NetworkEgressPortApplyConfiguration) WithPort(value int32) *NetworkEgressPortApplyConfiguration {
	b.Port = &value
	return b
}
