// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// NetworkEgressIPTargetApplyConfiguration represents a declarative configuration of the NetworkEgressIPTarget type for use
// with apply.
//
// NetworkEgressIPTarget is a single IPv4 or IPv6 address.
type NetworkEgressIPTargetApplyConfiguration struct {
	// Address is a single IP address.
	Address *string `json:"address,omitempty"`
}

// NetworkEgressIPTargetApplyConfiguration constructs a declarative configuration of the NetworkEgressIPTarget type for use with
// apply.
func NetworkEgressIPTarget() *NetworkEgressIPTargetApplyConfiguration {
	return &NetworkEgressIPTargetApplyConfiguration{}
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *NetworkEgressIPTargetApplyConfiguration) WithAddress(value string) *NetworkEgressIPTargetApplyConfiguration {
	b.Address = &value
	return b
}
