// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// RoutingPeerStatusApplyConfiguration represents a declarative configuration of the RoutingPeerStatus type for use
// with apply.
//
// RoutingPeerStatus defines the observed state of RoutingPeer.
type RoutingPeerStatusApplyConfiguration struct {
	// routingpeerID is the id of the created routing peer.
	RoutingPeerID *string `json:"routingPeerID,omitempty"`
	// networkID is the id of the network the routing peer was created in.
	NetworkID *string `json:"networkID,omitempty"`
	// The status of each condition is one of True, False, or Unknown.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// RoutingPeerStatusApplyConfiguration constructs a declarative configuration of the RoutingPeerStatus type for use with
// apply.
func RoutingPeerStatus() *RoutingPeerStatusApplyConfiguration {
	return &RoutingPeerStatusApplyConfiguration{}
}

// WithRoutingPeerID sets the RoutingPeerID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RoutingPeerID field is set to the value of the last call.
func (b *RoutingPeerStatusApplyConfiguration) WithRoutingPeerID(value string) *RoutingPeerStatusApplyConfiguration {
	b.RoutingPeerID = &value
	return b
}

// WithNetworkID sets the NetworkID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkID field is set to the value of the last call.
func (b *RoutingPeerStatusApplyConfiguration) WithNetworkID(value string) *RoutingPeerStatusApplyConfiguration {
	b.NetworkID = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *RoutingPeerStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *RoutingPeerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
