// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RoutingPeerSpecApplyConfiguration represents a declarative configuration of the RoutingPeerSpec type for use
// with apply.
//
// RoutingPeerSpec defines the desired state of RoutingPeer
type RoutingPeerSpecApplyConfiguration struct {
	NetworkRef         *ResourceReferenceApplyConfiguration  `json:"networkRef,omitempty"`
	DeploymentOverride *DeploymentOverrideApplyConfiguration `json:"deploymentOverride,omitempty"`
}

// RoutingPeerSpecApplyConfiguration constructs a declarative configuration of the RoutingPeerSpec type for use with
// apply.
func RoutingPeerSpec() *RoutingPeerSpecApplyConfiguration {
	return &RoutingPeerSpecApplyConfiguration{}
}

// WithNetworkRef sets the NetworkRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkRef field is set to the value of the last call.
func (b *RoutingPeerSpecApplyConfiguration) WithNetworkRef(value *ResourceReferenceApplyConfiguration) *RoutingPeerSpecApplyConfiguration {
	b.NetworkRef = value
	return b
}

// WithDeploymentOverride sets the DeploymentOverride field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeploymentOverride field is set to the value of the last call.
func (b *RoutingPeerSpecApplyConfiguration) WithDeploymentOverride(value *DeploymentOverrideApplyConfiguration) *RoutingPeerSpecApplyConfiguration {
	b.DeploymentOverride = value
	return b
}
