// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// SetupKeyStatusApplyConfiguration represents a declarative configuration of the SetupKeyStatus type for use
// with apply.
//
// SetupKeyStatus defines the observed state of SetupKey.
type SetupKeyStatusApplyConfiguration struct {
	// SetupKeyID of the setup key.
	SetupKeyID *string `json:"setupKeyID,omitempty"`
	// The status of each condition is one of True, False, or Unknown.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// SetupKeyStatusApplyConfiguration constructs a declarative configuration of the SetupKeyStatus type for use with
// apply.
func SetupKeyStatus() *SetupKeyStatusApplyConfiguration {
	return &SetupKeyStatusApplyConfiguration{}
}

// WithSetupKeyID sets the SetupKeyID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SetupKeyID field is set to the value of the last call.
func (b *SetupKeyStatusApplyConfiguration) WithSetupKeyID(value string) *SetupKeyStatusApplyConfiguration {
	b.SetupKeyID = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *SetupKeyStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *SetupKeyStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
