netbirdAPI:
  key: "nbp_1TpgsCUaF2BU3NVZfaDrGpoY1jx2iT2g7rWj"

operator:
  image:
    tag: "v0.1.0"

ingress:
  enabled: true
  router:
    enabled: true
  policies:
    default:
      name: Kubernetes Default Policy
      sourceGroups:
      - All
