ingress:
  enabled: true
  router:
    enabled: true
  policies:
    default:
      name: Kubernetes Default Policy
      sourceGroups:
      - All

netbirdAPI:
  # Replace with valid NetBird Service Account token (PAT)
  # https://docs.netbird.io/how-to/access-netbird-public-api#creating-an-access-token
  #key: "nbp_m0LM9ZZvDUzF8fpY50iChDOTxJgKFM3DIqmZ"
  # Use keyFromSecret instead of plain text secret
  keyFromSecret: "netbird-mgmt-api-key"

