name: Docker

on:
  push:
    tags:
      - "v*"
    branches:
      - main
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            netbirdio/kubernetes-operator
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Login to Docker Hub
        if: github.repository == github.event.pull_request.head.repo.full_name || !github.head_ref
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            "org.opencontainers.image.created={{.Date}}"
            "org.opencontainers.image.title={{.ProjectName}}"
            "org.opencontainers.image.version={{.Version}}"
            "org.opencontainers.image.revision={{.FullCommit}}"
            "org.opencontainers.image.version={{.Version}}"
            "maintainer=dev@netbird.io"
